### ISSUE TITLE
Trouble getting codegen to work

### ISSUE THREAD

**Issue by hwang123** [muuki88/sbt-graphql#21]
Hey guys, super new to graphql/sangria, so I apologize in advance if my issue is misplaced.

I am attempting to generate my result classes from a given `src/main/resources/schema.graphql` file containing the following lines:
```
type Query {
  transaction: Transaction!
}

type Transaction {
  name: String
  date: String
  id: ID!
}
```

My project/plugins.sbt file looks like this:
```
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.heroku" % "sbt-heroku" % "2.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.1")
addSbtPlugin("rocks.muki" % "sbt-graphql" % "0.5.0")
```

and build.sbt looks like this:
```
import rocks.muki.graphql.schema.SchemaLoader

name := "test"
version := "0.0.1"

scalaVersion := "2.12.4"
scalacOptions ++= Seq("-deprecation", "-feature")

libraryDependencies ++= Seq(
  "org.sangria-graphql" %% "sangria" % "1.3.0",
  "org.sangria-graphql" %% "sangria-circe" % "1.1.0",
  "org.sangria-graphql" %% "sangria-relay" % "1.4.1",

  "com.typesafe.akka" %% "akka-http" % "10.1.0",
  "de.heikoseeberger" %% "akka-http-circe" % "1.20.0",

  "io.circe" %%	"circe-core" % "0.9.2",
  "io.circe" %% "circe-parser" % "0.9.2",
  "io.circe" %% "circe-optics" % "0.9.2",
  "com.github.nscala-time" %% "nscala-time" % "2.18.0",

  "org.scalatest" %% "scalatest" % "3.0.5" % Test
)

Revolver.settings
enablePlugins(JavaAppPackaging)
enablePlugins(GraphQLSchemaPlugin, GraphQLQueryPlugin)
enablePlugins(GraphQLCodegenPlugin)

graphqlCodegenStyle := Sangria

val inputSchema = new File("src/main/resources/schema.graphql")
graphqlSchemas += GraphQLSchema(
  "transactions",
  "transactions schema",
  Def.task(
    SchemaLoader.fromFile(inputSchema).loadSchema()
  ).taskValue
)

graphqlCodegenSchema := graphqlRenderSchema.toTask("transactions").value
```

When I run 

`sbt graphqlCodegen` the operation succeeds and creates a bunch of new files inside of the target/ folder. Here is the success message: 
```
Harrisons-MacBook-Pro:coinecta-graphql-server harrisonwang$ sbt graphqlCodegen
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /Users/harrisonwang/.sbt/1.0/plugins
[info] Loading settings from assembly.sbt,plugins.sbt ...
[info] Loading project definition from /Users/harrisonwang/Desktop/coinecta/coinecta-graphql-server/project
[info] Loading settings from build.sbt ...
[info] Set current project to test (in build file:/Users/harrisonwang/Desktop/coinecta/coinecta-graphql-server/)
[info] Rendering schema to: /Users/harrisonwang/Desktop/coinecta/coinecta-graphql-server/target/graphql/transactions.graphql
[info] Generate code for 1 queries
[info] Use schema /Users/harrisonwang/Desktop/coinecta/coinecta-graphql-server/target/graphql/transactions.graphql for query validation
[success] Total time: 1 s, completed May 18, 2018 11:26:01 PM
```
Unfortunately, none of these files (to my knowledge) contain the desired generated code; by reading the docs, I expected the result classes to live in a package called `graphql.codegen`. The file `target/scala-2.12/classes/graphql/codegen/GraphQLCodegen.class` has the correct package name, but the file itself is empty: 
```
package graphql.codegen
object GraphQLCodegen extends scala.AnyRef {
}
```
I think the command is accessing the correct `schema.graphql` file, because it creates a new file `target/graphql/transactions.graphql` which contains the same schema, so I am not sure where my mistake in the process is.
 
If anyone could give me any tips/pointers on how to get the code generation working properly, it would be much appreciated. Sorry for the lengthy post, but I wanted to provide as much context as possible. Thanks a bunch!

**Comment by muuki88** [comment]
Thanks for the lengthy post 🤗🤩 context is the best for figuring out what's wrong.

From a high level perspective everything looks good ( really clean `build.sbt` 👍 ). Can you try what happens if you comment out

```scala
graphqlCodegenStyle := Sangria
```

I really chose a very confusing name. The Apollo style has nothing to do with the implementation, but how things looks. We recommend this default style.

You can also try to build up your build.sbt from the test-project or a scripted test from the repo.

At this point I'm not sure if this is a bug or a misconfiguration 🤔

**Comment by hwang123** [comment]
Thanks for the quick response!

I tried commenting out the line you suggested, but still have the same results :/ . I'll try building up the build.sbt from the test project like you suggested and see if I can isolate the problem. If that doesn't work, can I send you over a zip of my project? Of course no worries if you're pressed on time, but I figured it might be more efficient than trading comments since I'm pretty unfamiliar with this stuff. Thanks again!

**Comment by muuki88** [comment]
Awesome 😎 

Yeah, you can create a public git repo and I'll check that out and see if I find anything suspicious. Won't be able to do that today unfortunately 😬

**Comment by muuki88** [comment]
@hwang123 did you have any luck finding out the issue?

**Comment by hwang123** [comment]
Unfortunately not after doing a quick pass over the weekend. I won't be able to look into things in too much depth for a couple days, but my guess is that the issue is a config typo on my end. I'm planning on building up a sample project from scratch when I can circle back to this project to isolate the problem. If you want to close this out for now, I can reach out / reopen it if I still have trouble when I take a more in depth stab at it later in the week.

**Comment by muuki88** [comment]
Sounds reasonable 👍

**Comment by markarasev** [comment]
I have a similar problem. I created a [minimal project](https://github.com/markarasev/graphql-codegen-test) just following the docs and when running `sbt graphqlCodegen` I have the expected `starwars.graphql` file in `target/graphql` directory but only this generated scala code in `target/scala-2.12/src_managed/sbt-graphql/GraphQLCodegen.scala` :
```
package graphql.codegen
object GraphQLCodegen
```
Here's the sbt logs :
```
[info] Rendering schema to: /Users/marckarassev/Desktop/bd4m/graphqlCodegen-test/target/graphql/starwars.graphql
[info] Introspect graphql endpoint: http://try.sangria-graphql.org/graphql
[info] Generate code for 0 queries
[info] Use schema /Users/marckarassev/Desktop/bd4m/graphqlCodegen-test/target/graphql/starwars.graphql for query validation
[info] Generating json decoding with: None$
```

**Comment by muuki88** [comment]
Your test project doesn't contain any graphql files. The log output mentions this :

```
[info] Generate code for 0 queries
```

You need to have actual queries.

Out of curiosity: why did you use the "Sangria" style?

**Comment by markarasev** [comment]
Should not it use the introspected `target/graphql/starwars.graphql` file ?
Maybe I'm getting this project wrong, I'm looking for something that would generate the sangria case classes from a `.graphql` file.

**Comment by muuki88** [comment]
I think I understand your confusion now! Correct me if I'm wrong:
> You want case classes for every object/input type with all fields that are defined in your schema.

This is not how this plugin works and IMHO not as graphql is supposed to be used.

A case class is generated from two inputs

1. A `graphql` file, like [these in the test project](https://github.com/muuki88/sbt-graphql/tree/master/test-project/client/src/main/graphql). The query contains the fields that should be resolved and the optional input variables.
2. A graphql schema, which is used to get the type information for the requested fields in the `graphql` query file

This means a case class is always bound to a single `graphql` query file, which is one of the core ideas of graphql. You only request the data you are interested in. The case class represents exactly the query fields.

Does this help :smile:

**Comment by markarasev** [comment]
Thanks for your answer, I think I'm starting getting it 😁

> I think I understand your confusion now! Correct me if I'm wrong:
>> You want case classes for every object/input type with all fields that are defined in your schema.

Yes you're right.

> This means a case class is always bound to a single graphql query file

So this is client side code generation ?

> This is not how this plugin works and IMHO not as graphql is supposed to be used.

I would be interested to hear more about this, but maybe here is a wrong place to have this discussion.

**Comment by muuki88** [comment]
Yes, this is client side code generation 😊
