### ISSUE TITLE
Scripted tests

### ISSUE THREAD

**Issue by jonas** [muuki88/sbt-graphql#3]
It would be nice to have scripted tests for the plugin. I'm not currently sure how to manually test things using the test-project.

**Comment by muuki88** [comment]
Totally! This is one of the next things I try to do.

Regarding the test project you can simply start SBT in the folder. If you change any code in the plugin you need to reload the test project SBT shell.

**Comment by muuki88** [comment]
I'll try to fix this one in the next days
