### ISSUE TITLE
Fix generation of interfaces

### ISSUE THREAD

**Issue by jonas** [muuki88/sbt-graphql#32]
The scalameta source generator currently has an `emitInterfaces` flag which allows to generate a Scala `trait` for each GraphQL fragment. The initial goal was to make it easier to use the generated code by coding against "interfaces" rather than the "unique" result classes that is currently generated.

The code was disabled in https://github.com/mediative/sangria-codegen/pull/11 since it still requires some work to support fragment with nested selections, e.g.:

```graphql
fragment ArticleWithAuthorFragment on Article {
  title
  author {
    ...IdFragment
    ...AuthorFragment
  }
}
```

Alternatively if this is not actually useful for users, the related code could just be removed.

**Comment by muuki88** [comment]
This should be fixed with #45
