### ISSUE TITLE
Generate circe Encoder for query Variables

### ISSUE THREAD

**Issue by felixbr** [muuki88/sbt-graphql#35]
Hey,

currently only Decoder instances for the returned graphql result are generated. But the input variables of the query are usually sent via json to graphql as well.

It would be beneficial to add the Encoder derivation for the Variables case class.

I'm not intimately familiar with the graphql spec, so I'm not sure whether input variables can be nested, but if not deriving the Encoder for the top-level Variables case class might be enough.

**Comment by Krever** [comment]
I just hit this issue and will try to implement it. Doesn't look too hard.
