### ISSUE TITLE
Generate code from queries

### ISSUE THREAD

**Issue by jonas** [muuki88/sbt-graphql#4]
Similar to [apollo-codegen](https://github.com/apollographql/apollo-codegen) it would be nice to generate domain classes from queries against a schema.

A lot of this has been prototyped in [sangria-codegen](https://github.com/mediative/sangria-codegen), however, the code generator should ideally use Sangria's AST directly instead of an [intermediate representation](https://github.com/mediative/sangria-codegen/blob/master/sangria-codegen/src/main/scala/com.mediative.sangria.codegen/Tree.scala) based on an initial [pass](https://github.com/mediative/sangria-codegen/blob/master/sangria-codegen/src/main/scala/com.mediative.sangria.codegen/Importer.scala).

Open questions:
 - Is it OK to use [scala.meta](https://github.com/mediative/sangria-codegen/blob/master/sangria-codegen/src/main/scala/com.mediative.sangria.codegen/ScalametaGenerator.scala) for the code generation itself?
 - Is generation of traits from interfaces a "must have"? In the sangria-codegen project they were temporarily disabled to ensure progress. (see https://github.com/mediative/sangria-codegen/issues/12)

**Comment by muuki88** [comment]
Wow! This looks very promising :sunglasses: 
This looks as straightforward as I hoped too. I'm really looking forward to see this in action.

**Comment by jonas** [comment]
Pushed an initial port of the sangria-codegen code [here](https://github.com/jonas/sbt-graphql/tree/codegen). Will look into whether it is possible to replace scalameta with something simpler that still helps to format the code in terms of indentation.

**Comment by muuki88** [comment]
Wow :heart_eyes: That looks amazing. The tests are really helpful to see the output compared to the input graphql query.

Are you planning to add the query into the object itself as well? The apollo-codegen does a nifty thing. It provides a marker interface for queries that all queries extend. For us this could look something like

```scala
trait GraphQLQuery {
  query: Document
  type Variables
  type Data
}
```

This allows users to build generic clients for queries, e.g.

```scala
def execute(query: GraphQLQuery)(variables: query.Variables): Future[query:Data] = ???
```

**Comment by jonas** [comment]
That sounds like a good interface. And should also cover the case where the client must use named queries.

**Comment by muuki88** [comment]
@jonas would you mind opening a pull request with your ported code here?
I tinkered a bit around with the code and extended the `test-project`. I would try to
add the interface I proposed above in the code generation as well. WDYTH?

**Comment by jonas** [comment]
Yes, will do after a rebase and update of the commit message.
