### ISSUE TITLE
Additional imports are quoted and therefore broken

### ISSUE THREAD

**Issue by felixbr** [muuki88/sbt-graphql#57]
With the new 0.10.1 release I have a problem with "additional imports". The imports are still inserted into the generated sources, but now have back-ticks that aren't correct:

Additional imports:
```sbt
graphqlCodegenImports ++= Seq(
  "java.time._",
  "io.circe.java8.time._",
),
```

Compiler complains:
```
[error] SomeGeneratedSourceFile.scala:2:8: not found: object java.time
[error] import `java.time`._
[error]        ^
[error] SomeGeneratedSourceFile.scala:3:8: not found: object io.circe.java8.time
[error] import `io.circe.java8.time`._
[error]        ^
```

My guess is that scalameta thinks that `java.time` is one big identifier instead of a package path and therefore quotes it.

**Comment by muuki88** [comment]
Introduced in #53 
cc: @ngbinh

**Comment by ngbinh** [comment]
I will take a look at this tomorrow.

**Comment by muuki88** [comment]
@ngbinh already had a change to do so :smile: #58

**Comment by ngbinh** [comment]
Thanks!

**Comment by felixbr** [comment]
Thank you :)
