### ISSUE TITLE
Yet another trouble getting codegen to work 

### ISSUE THREAD

**Issue by sean-lawfully** [muuki88/sbt-graphql#67]
Hello,

I'm having a world of trouble trying to generate scala code from a graphql schema at the moment.
So basically, my company runs a Python based graphql server and what I'm trying to do is to download the schema from it and generate Scala code using sbt-graphql.

I was able to get the schema by using graphql-cli. (schema.graphql)
It's a single file with all types and enums included.
Could you please help me learn what to do next?
In other posts I read that queries should be in separate .graphql files, but how would I separate this schema file to those?
If I just follow the README here, "sbt graphqlCodegenSchema" generates files but I don't see any that are related to my schema.

Please help...

**Comment by Krever** [comment]
Hey @sean-lawfully 

From what I learned recently, this plugin allows you to generate code for concrete queries you want to use in your code. So beside the general schema that describes what operations are possible you need a separate file with specific queries that includes things like filters, variables, returned fields and so on. Once you have those and your schema, then sbt-graphql will generate common types from schema and specific types from queries. Does it make sense?

**Comment by muuki88** [comment]
@Krever thanks for you answer and sorry @sean-lawfully for the very late response.

What @Krever says is correct. The plugin generates types for queries. What would expect to get from a schema?
