### ISSUE TITLE
Stable ordering of output

### ISSUE THREAD

**Issue by anagrius** [muuki88/sbt-graphql#80]
Hey, thanks for doing this project!

We have used it to secure stability of our API and detect changes to the API in PRs at Humio.

I was wondering if it would be possible to make the ordering of the entries in the generated schema stable.

Currently if you change the order of fields in Sangria, it will also change in the output.

We can sort the in code, but it would be useful in the plugin, so reordering does not trigger a false positive for out "API change" check.

**Comment by felixbr** [comment]
Have you considered using `sangria` directly for that? There is `Schema#compare` and `SchemaChange#breakingChange` which makes it fairly easy to compare two schemas for breaking changes (semantically, not just comparing strings).

We use this @gutefrage to prevent breaking changes and it works very well. Just one integration test which compares the `Schema` in the commit with the `Schema` from production.

Looks like that:
```
  test(s"The current schema must not have breaking changes compared to the production schema at $host") {
    productionSchema: Schema[Any, Any] =>
      pendingIfBreakingChangeExpected {
        forAll(ApiKey.FullAccess.schema compare productionSchema) { change =>
          assert(!change.breakingChange, s"The change '$change' is a breaking change!")
        }
      }
  }
```

**Comment by anagrius** [comment]
Thank for the tip. @felixbr

**Comment by muuki88** [comment]
@anagrius happy to hear that you use this plugin in production :heart: 

As @felixbr correctly mentioned it is easier to implement this in an integration test than provide this feature. You have more flexibility as is usually easier to grasp that anything that has to do with sbt :wink:
