### ISSUE TITLE
Schema generation from Introspection

### ISSUE THREAD

**Issue by gschambial** [muuki88/sbt-graphql#83]
Hi Guys, 

 I am trying to generate a `schema file` which is a combination of Local Schema and Results of an Introspection:

```
graphqlSchemaSnippet := "demo.StaticSchema.schema"

target in graphqlSchemaGen := target.value / "graphql"
```

Above config generates, `.schema` file from my Local Schema. I also want to generate a schema file from my introspection result

```
graphqlSchemas += GraphQLSchema(
  "Remote",
  "Remote Schema",
  Def.task(
    GraphQLSchemaLoader
      .fromIntrospection("http://localhost:8081/graphql", streams.value.log)
      .loadSchema()
  ).taskValue
)
```

But, after running ` sbt graphqlSchemaGen` i don't see any intropection schema? I guess i am missing some piece and not able to figure out from documentation. 

Any help would be appreciated. Thanks

**Comment by muuki88** [comment]
Hi @gschambial . So already figured this out :joy: ?

**Comment by gschambial** [comment]
> Hi @gschambial . So already figured this out 😂 ?

Haha, Yes. I was not rendering schema simply loading it.

**Comment by gschambial** [comment]
However, i am wondering if there is a way to render both schemas in 1 file (Local + Remote from introspection)

**Comment by muuki88** [comment]
This plugin can't do this. IMHO this also not trivial as merging two schema is a whole graphql universe (schema stitching).

Out of curiosity: What is the use case for this?

**Comment by gschambial** [comment]
@muuki88 

I have following scenario:

1 backend app --> 2 backend with GQL --> 3 backend with GQL

and I was trying to create models for 2+3's schema in app no.2 that can be used by app no 1. (Very vague idea 👻)

However, I don't think I need to do this way as each app i.e. app 2 and app 3 can generate models for their own queries and can be included by app 1.
