### ISSUE TITLE
Examples for common use-cases

### ISSUE THREAD

**Issue by felixbr** [muuki88/sbt-graphql#86]
While the documentation in the readme is generally good, the plugin now supports multiple independent features, so it's harder to understand the big picture. Recent issues (#83, #84, #85) are all at least in part about misunderstanding/confusing the plugin features.

Imo it would be nice to have examples for common use-cases like:

- I want to connect to an existing GraphQL-api and want to generate the Scala-types from my queries
- I'm writing a GraphQL-api (using `sangria`) and want to render the schema as a file
- I have existing queries and a schema and just want to validate they match via `sbt`
- I have a repository with both server/client, how do I use the plugin with that

I think we could add a new folder `examples` and put a minimal project for each use-case there and link them from the readme.

(Maybe we could even sneak in an example of our `BreakingChangeSuite`, as the topic comes up sometimes and it would be nice to have something to link to)

@muuki88 WDYT?

**Comment by muuki88** [comment]
That sounds good. Especially making this more prominent. There's already the [test-project|https://github.com/muuki88/sbt-graphql/tree/master/test-project], but that's non-obvious and not documented.

**Comment by jbek7** [comment]
Does the plugin provide Graphql SDL to Scala code?  Similar to https://github.com/99designs/gqlgen ?

**Comment by muuki88** [comment]
Nope :smile:

**Comment by jbek7** [comment]
Are you aware of any such plugin/tool?

**Comment by felixbr** [comment]
There have been discussions about this use-case in `sangria` issues. I don't know the current state but here's an issue with a lot of suggestions and links: https://github.com/sangria-graphql/sangria/issues/381
