### ISSUE TITLE
Multiple schemas generation, is it possible?

### ISSUE THREAD

**Issue by s3ni0r** [muuki88/sbt-graphql#91]
Hi,
I need to maintain two seperate graphql schemas (public and private) in the same project, is it possible to define multiple graphqlSchemaSnippet ?
Thanks!

**Comment by felixbr** [comment]
Yes, in general it is possible. The `graphqlSchemas` key is a list of schemas. They are referred to via the label you give them.

See: https://github.com/muuki88/sbt-graphql#schema-definitions

**Comment by s3ni0r** [comment]
Yes, i was talking about schema generation, the sub-modules solution was considered, but it's too expensive to implement.
thank you for your answer and guidelines :)!

**Comment by felixbr** [comment]
```
lazy val privateSchemaGen = (project in file("privateSchemaGen"))
  .enablePlugins(GraphQLSchemaPlugin)
  .settings(
    graphqlSchemaSnippet := "my.project.schema.PrivateSchema"
  )
  .dependsOn(main) // or whatever your main module is called
```

I haven't tested this, but something like this could do the trick even without moving code around and you can call it via `privateSchemaGen/graphqlSchemaGen`.

**Comment by s3ni0r** [comment]
I spent some time trying to implement your suggestion, but i end up each time with a weird error.
```
sbt:some-api> privateSchemaGen/graphqlSchemaGen
[info] running graphql.SchemaGen xxx/privateSchemaGen/target/sbt-graphql/schema.graphql
[error] (run-main-0) java.lang.NoSuchMethodError: sangria/schema/PossibleInterface$.convert(Lsangria/schema/InterfaceType;Lsangria/schema/PossibleType;)Lsangria/schema/PossibleInterface; (loaded from file:xxx/.coursier/cache/v1/https/repo1.maven.org/maven2/org/sangria-graphql/sangria_2.12/1.4.2/sangria_2.12-1.4.2.jar by URLClassLoader with NativeCopyLoader with RawResources(
```
the convert function doesn't exist since version 1.3.x, and we are using sangria version 1.4.2 with plugin version 0.14.0.

Also when i try to generate a single schema on the root project without any submodules, it works with the same library and plugin versions.

**Comment by felixbr** [comment]
That's a shame. I don't have time to dig into this right now. The only thing I can think of is that your submodule is missing the sangria dependency somehow?

In any case we should probably look into this as having more than one schema is not really a rare thing. At our company we have multiple schemas as well but they are all subsets of a "master" schema, which is the only one we generate the schema-file for (the file is only used for code-review, so it's not too important).

**Comment by s3ni0r** [comment]
i will investigate more and try to explain the root of the problem once resolved :)

**Comment by s3ni0r** [comment]
So yeah , for whatever reason my root project was pulling sangria version 2.0.0-M3 and the submodule was pulling version 1.4.0, i have run ``` show evicted``` to detect that and used a temporary dependencyOverrides to force sangria version to 1.4.0 to test if your suggestion works.
```
dependencyOverrides ++= Seq(
      "org.sangria-graphql"         %% "sangria"                  % "1.4.0",
    )
```
Now it works perfectly :+1:, Thank you! @felixbr for your time and help :).

**Comment by felixbr** [comment]
Awesome, I'm glad it works for you now! :)
