### ISSUE TITLE
Weird published version v0.1.6

### ISSUE THREAD

**Issue by jtjeferreira** [muuki88/sbt-graphql#96]
I think https://github.com/muuki88/sbt-graphql/releases/tag/v0.1.6 should have been `0.16.0`. Also the release title (v1.6.0)  is not right. Maybe cut a new version to avoid confusion?

**Comment by muuki88** [comment]
Oh damn! That's right. Will fix that on Monday 😃 thanks for pointing out 😊

**Comment by muuki88** [comment]
Fixed :)
