### ISSUE TITLE
Question about code generation issue in test phase

### ISSUE THREAD

**Issue by haxkil** [muuki88/sbt-graphql#97]
Hi @muuki88. Thank you for the nice plugin!

I'm using pretty default sbt-graphql configuration in Play project. Ran into issue with code generation, which happens only in test phase with error similar to: `Symbol 'type graphql.codegen.types.myInputType' is missing from the classpath.`
I think this may be related to the different generated `Interfaces.scala` files in `/main` and in `/test`

```scala
/* ../web/target/scala-2.13/src_managed/main/sbt-graphql/Interfaces.scala */
package graphql.codegen
import io.circe.{ Decoder, Encoder }
import io.circe.generic.semiauto.{ deriveDecoder, deriveEncoder }
object types {
  case class myInputType(questionId: Option[String], userAnswers: List[String])
  case object myInputType {
    implicit val jsonDecoder: Decoder[myInputType] = deriveDecoder[myInputType]
    implicit val jsonEncoder: Encoder[myInputType] = deriveEncoder[myInputType]
  }
}
```
Classes are missed in file generated in `/test`

```scala
/* ../web/target/scala-2.13/src_managed/test/sbt-graphql/Interfaces.scala*/
package graphql.codegen
import io.circe.{ Decoder, Encoder }
import io.circe.generic.semiauto.{ deriveDecoder, deriveEncoder }
object types
```

Any help would be greatly appreciated!

**Comment by felixbr** [comment]
Seems weird to me that it generated code for test separately. In our project we don't have a `src_managed/test` folder, only `src_managed/main`. 😐

**Comment by andrei-hruzdzeu** [comment]
@felixbr thank you! Followed your advice and creating sub-project within Play app solved the issue.

**Comment by haxkil** [comment]
@felixbr thank you! Followed your advice and creating sub-project within Play app solved the issue.

**Comment by benwaffle** [comment]
Thanks, putting the generated code in a separate project fixed it. But I think that this is still a bug. We shouldn't be generating the same class twice (`graphql.codegen.types`), especially twice with different contents. I'm not sure what the solution is here though...

**Comment by benwaffle** [comment]
The subproject idea fixed it in sbt for me, but not in IntelliJ. Here's the fix I'm using now:

```
Test / graphqlSchemaGenFilter := SchemaFilters.WithoutGraphQLBuiltIn
```

**Comment by benwaffle** [comment]
@muuki88 what do you think about making `types` into a `package` instead of an `object`? That way you can generate it in both main and test without conflicts about which classes are inside. I'm not sure where things like `type ID = String` would go though...

**Comment by muuki88** [comment]
I'm all for changes that make this easier to use. I haven't quite understand the setup though.

Code that's been generated in main should be usable in test. Generating code in test would mean for me that there are additional queries that are not used in production.

Configuring different output packages should be, IIRC, possible for Test and Compile scope. Would that help?
